sudo: false


language: node_js
node_js:
  - 8.5.0

env:
  - BROWSER=ChromeCi
  - BROWSER=Firefox

script:
  - npm run test

after_script:
  - npm run coveralls

jobs:
  include:
    - stage: ghpages
      script: npm run pages
      deploy:
        provider: pages
        skip-cleanup: true
        github-token: $GITHUB_TOKEN
        keep-history: true
        local-dir: assets
        on:
          branch: master
    - stage: deploy
      script: npm run build
      deploy:
        provider: npm
        email: supermanchc@gmail.com
        api_key: $NPM_KEY
        skip-cleanup: true
        on:
          branch: master

# You can specify the order for stages
stages:
  - test
  - ghpages
  - name: deploy
    if: tag IS present # conditional build, only deploy when tag is present
