sudo: false


language: node_js
node_js:
  - 8.5.0

env:
  - BROWSER=ChromeCi
  - BROWSER=Firefox

script:
  - npm run test && npm run build

after_script:
  - npm run coveralls

deploy:
  provider: npm
  email: supermanchc@gmail.com
  api_key: $NPM_KEY
  skip-cleanup: true
  on:
    tag: true

